### ISSUE TITLE
How to handle policies

### ISSUE THREAD

**Issue by rbruhn** [laravel-auto-presenter/laravel-auto-presenter#101]
I'm running into an issue when implementing Policies in blade templates. For example, I use a presenter with Group: @can('isOwner', $group) and it checks if the current user is the owner of the group. It's being viewed as the wrapped presenter object and not checking the Policy at all.
Is there a way to access the original object?

**Comment by rbruhn** [comment]
Found it. getWrappedObject()

**Comment by rbruhn** [comment]
Ok, no I didn't. That doesn't seem to work.

**Comment by axeloz** [comment]
Thanks @rbruhn, I was about to post a ticket about this matter.
