### ISSUE TITLE
Accessing undefined variables/methods causes problems in Twig

### ISSUE THREAD

**Issue by unitedworx** [laravel-auto-presenter/laravel-auto-presenter#26]
I am using twig instead of blade as template engine and accessing undefined variables causes problems in Twig. If you try to output a variable that is not there with twig the default behavior is to output nothing. However since your Base Presenter throws an exception if a variable/method does not exist this breaks things!

twig will translate {{ content.subpages }} to $content->subpages and if this does not exist it will try $content->subpages(); and if this is not found either it wont complain and simply wont output anything

Unless there is a specific reason you are trowing an exception you should remove the below line to make this compatible with twig. i believe this will be a problem in Blade as well? not sure if blade haves the same way. 

```
in BasePresenter.php 
public function __call($key, $args)
the following line should be removed.
        throw new ResourceMethodNotFoundException('Presenter: '.get_called_class().'::'.$key.' method does not exist');
```

**Comment by mmodler** [comment]
This might be "correct" behaviour, but i don't understand why twigbridge (without autopresenter) can handle undefined vars/methods and with autopresenter it breaks...

@unitedworx How did you solve this issue?

**Comment by unitedworx** [comment]
the problem is caused since this presenter throws an exception when it does not find a method!

my solution was to use another presenter package Laracasts\Presenter. Its a bit less magical(you call the presenter method and then what you need on the model) but i always know when i use the presenter since i do {{ post.presenter().date }} which is better imho

if on the other hand you you need to keep using this package then you can modify it yourself and remove the above i suggested. or make sure that laravel exception handler in app\Exception\Handler continues execution when  exception ResourceMethodNotFoundException is raised (not 100% sure on this)!

**Comment by mmodler** [comment]
We tried to modify the exception handling, but in the handler the exception comes up as "ErrorException", only the "previous" -> "previous" exception is "ResourceMethodNotFoundException". I think twig/twigbridge is wrapping the original exception and gave up finding a solution in the exception handler...

**Comment by unitedworx** [comment]
Just do the change mentioned in the first post to solve your problem! For now! Then your options are to either keep patching this yourself each time the package gets updated or try and get the developer to reason an remove this! If not then laracasts\presenter will play much better and ant cause problems with twig

**Comment by mmodler** [comment]
Thnaks! We switched to laracasts\presenter yesterday - a bit less magical but no unacceptable changes to non-presented-model behavior.

**Comment by unitedworx** [comment]
No problem glad this helped
