### ISSUE TITLE
PHP 5.4 support

### ISSUE THREAD

**Issue by rkgrep** [laravel-auto-presenter/laravel-auto-presenter#76]
Is PHP 5.5 required only because of `finally` and `::class` usage in tests?
Because tests run quite good in 5.4 environment https://travis-ci.org/rkgrep/laravel-auto-presenter/jobs/64636236

I'm not a fan of old-versioned apps, but having package depending on tests is something wrong.

**Comment by GrahamCampbell** [comment]
Sorry. php 5.4 support isn't planned.

**Comment by GrahamCampbell** [comment]
Laravel 5.1 is php 5.5+ only and php 5.4 is EOL in a few month's time.
