### ISSUE TITLE
Using Aliases? - just a (nagging) question

### ISSUE THREAD

**Issue by guile** [laravel-auto-presenter/laravel-auto-presenter#77]
I want to do something simple, like aliasing database-returned attributes with metphor-based attributes
e.g. created_at can also be accessed by DateOfJoining or DoJ
created_at is decorated as a method in my presenter. How can I add "DoJ" so it simply returns or calls created_at method. The method has to be added to the presenter, obviously, which is why it's a query here.

**Comment by GrahamCampbell** [comment]
I don't understand the question? You've just described how to do what you want?

**Comment by jbrooksuk** [comment]
If you mean that you want to share methods across several presenters, use a trait. We [do this](https://github.com/cachethq/Cachet/blob/master/app/Presenters/Traits/TimestampsTrait.php) in Cachet.
