### ISSUE TITLE
Mail Queue and Array Access

### ISSUE THREAD

**Issue by aronduby** [laravel-auto-presenter/laravel-auto-presenter#78]
My user model has a `first_name` and `last_name` field, and I'm using this class to create a `name` property. This works out great until I have to run it through `Mail::queue` which apparently requires the data in the view to be accessed as an array instead of object. But, if I do that than I get `Cannot use object of type App\Presenters\User as array`. 

Using `redis` driver if that matters.

**Comment by GrahamCampbell** [comment]
You need to make your presenter implement array access if you want to use it as an array.

**Comment by aronduby** [comment]
Seems like something that should be in the base if we're decorating models which already have array access. 

I've also found it's not quite that easy when it comes to the queue. The model is getting serialized, so it's `toArray` function is being called, which won't include these properties. I'm currently looking into how to get that to work. Any suggestions?

**Comment by aronduby** [comment]
not sure how to reference issues in pull requests or vice-verse but I've submitted a pull request -  https://github.com/laravel-auto-presenter/laravel-auto-presenter/pull/79
