### ISSUE TITLE
Decorate Pagination issue

### ISSUE THREAD

**Issue by k1ng440** [laravel-auto-presenter/laravel-auto-presenter#85]
```
        use McCool\LaravelAutoPresenter\Facades\AutoPresenter 
        $model = MyModel::where('status', '1')->paginate();
        AutoPresenter::decorate($model)->toArray();

        ```

result: 

```
{
    total: 24,
    per_page: 50,
    current_page: 1,
    last_page: 1,
    next_page_url: null,
    prev_page_url: null,
    from: 1,
    to: 24,
    data: [
        { },
        { },
        { },
        { },
        { },
        { },
        { },
        { },
        { },
        { },
        { },
        { },
        { },
        { },
        { },
        { },
        { },
        { },
        { },
        { },
        { },
        { },
        { },
        { }
    ]
}
```

**Comment by GrahamCampbell** [comment]
What happens if you do this:

```php
AutoPresenter::decorate($model->toArray());
```

**Comment by GrahamCampbell** [comment]
Or just `$model->toArray()`.

**Comment by k1ng440** [comment]
I get the data i supposed to get with ``` $model->toArray() ``` or ``` AutoPresenter::decorate($model->toArray()); ``` but its not decorated.

**Comment by jbrooksuk** [comment]
This is happening for me too.

**Comment by GrahamCampbell** [comment]
Maybe this is something Laravel recently broke? Is it working on earlier Laravel versions?

**Comment by jbrooksuk** [comment]
Cachet still seems to be working.

**Comment by GrahamCampbell** [comment]
> but its not decorated.

Note that decoration is typically not done in place. We clone stuff first, so getting the value out of the decorate function is important.

**Comment by k1ng440** [comment]
oh right. so think you can fix it please? I tried to fix it myself and send pull request but i lost in loops.

**Comment by jbrooksuk** [comment]
Two things:

1. Is your presenter extending the `BasePresenter` class?
2. Implement `Arrayable`, that seemed to help me.

**Comment by k1ng440** [comment]
@jbrooksuk  Implement Arrayable to what? Model or Presenter?

**Comment by jbrooksuk** [comment]
The presenter @k1ng440
