### ISSUE TITLE
Eloquent Accessors

### ISSUE THREAD

**Issue by ilvalerione** [laravel-auto-presenter/laravel-auto-presenter#86]
Hello Graham,
What's the difference with Eloquent Accessors?

https://laravel.com/docs/master/eloquent-mutators#accessors-and-mutators

Thanks for your support.

**Comment by eberkund** [comment]
Presenters will only apply when you use them from a view. The idea is 

1. You keep formatting related stuff out of your model
2. You use the raw data in your controllers but the formatted data in your views

**Comment by GrahamCampbell** [comment]
You can always call the presenter facade yourself to present something manually.

The main idea here is to separate that stuff so your model class isn't full.

As @eberkund says, one use case is to only use it for views (probably the main one), but that's not the only one, as just mentioned. :)
