### ISSUE TITLE
Applying a presenter to relations of a model that does not have a presenter

### ISSUE THREAD

**Issue by rickselby** [laravel-auto-presenter/laravel-auto-presenter#89]
Say I have a model `User` that doesn't have an associated presenter. A `User` can have multiple `Posts` - and the `Post` model _does_ have a presenter. If I only pass a `User` to a page, the related `Posts` will not be decorated because the parent Model can't be decorated.

Would it be reasonable to add a `ModelDecorator` to check though each model? I see the `AtomDecorator` does this, but this is only called for classes that implement `HasPresenter`.

**Comment by GrahamCampbell** [comment]
Not sure how common that use case is.

**Comment by rickselby** [comment]
Yeah, in all the years of this package I'm the first person to bring it up. I've got a local decorator to catch this case, and can put together a pull request if you decide to add it to the repo.
