### ISSUE TITLE
Relations are not decorated when the model has no presenter

### ISSUE THREAD

**Issue by lazychaser** [laravel-auto-presenter/laravel-auto-presenter#9]
If model has no presenter, inner relations do not get decorated, too.

**Comment by jorenvanhee** [comment]
I think this is an issue again in the current version.

I have a model with child models (eager loaded) that should be decorated. The AtomDecorator should take care of this. But the canDecorate method never returns true, since the root model doesn't implement the HasPresenter interface.

I hope this makes sense.

**Comment by GrahamCampbell** [comment]
This was intentionally changed back.

**Comment by GrahamCampbell** [comment]
This is basically due to the fact we want models to be immutable from the perspective of autopresenter.

**Comment by jorenvanhee** [comment]
Thanks for the quick reply. What is the recommended solution for decorating child models? Decorate them manually or implementing the HasPresenter interface on the parent model.

**Comment by GrahamCampbell** [comment]
Maybe we need an interface that allows relations to be decorated?

**Comment by jorenvanhee** [comment]
Yep. And maybe with a method that returns an array, with the relations that should be decorated.

**Comment by GrahamCampbell** [comment]
I don't agree there. We should always decorate if we can. I think it would be stupid to allow people to mess with that.

**Comment by jorenvanhee** [comment]
I guess I don't understand why the relations aren't decorated by default. But if a simple interface does the job, that's ok for me. I just see myself having to add it to a lot of models.

For instance, I'm working on a project with shopping carts, cart items, products, product categories. So I would need the HasPresenter interface on the product model. And the new interface on all the other models.

**Comment by GrahamCampbell** [comment]
Hmmm, maybe this does need to change. Leave it with me. I have another idea that I think you will like.
