### ISSUE TITLE
Add option to define presenters outside of models

### ISSUE THREAD

**Issue by rickselby** [laravel-auto-presenter/laravel-auto-presenter#90]
I'm not keen on tying the presenter and model so tightly, nor having the model be aware of how it is to be presented. I've implemented an alternative; to define 'mappings' of classes and presenters in a service provider instead:

https://github.com/rickselby/laravel-auto-presenter-mapper

If this functionality is something you'd be happy to add to your package, I can refactor it appropriately and make a pull request.

**Comment by deleugpn** [comment]
Definitely an interesting approach. Both options in a single package would be great, I think.

**Comment by GrahamCampbell** [comment]
I think I'm happy with this package as it is. For the other behaviour, we have your package. :)
