### ISSUE TITLE
I have problem with package 

### ISSUE THREAD

**Issue by congas1983** [laravel-auto-presenter/laravel-auto-presenter#96]
**////// model person** <br />
<?php<br />

namespace App\Models\Transv;<br />
use App\Models\Emp\Entrepreneur;<br />
use App\Presenters\PersonPresenter;<br />
use McCool\LaravelAutoPresenter\HasPresenter;<br />
use Illuminate\Database\Eloquent\Model;<br />

class Person extends Model implements HasPresenter {<br />
/**<br />
    * function presenter model Person<br />
    *  Design Pattern<br />
    */<br />
    public function getPresenterClass()<br />
    {<br />
        return PersonPresenter::class;<br />
    }<br />
}<br />
<br />

**/////// PersonPresenter /////**<br />

<?php namespace App\Presenters;<br />

use App\Models\Transv\Person;<br />
use McCool\LaravelAutoPresenter\BasePresenter;<br />

class PersonPresenter extends BasePresenter<br />
{<br />

   function __construct(Person $resource)<br />
    {<br />
     $this->wrappedObject = $resource;<br />
    }<br />

    public function full_name()<br />
    {<br />
      return trim($this->wrappedObject->first_name . ' ' .$this->wrappedObject->second_name. ' '.$this->wrappedObject->last_name);<br />
    }<br />

}<br />

- `<br />`

- 

**/// in my controller ////**<br />
namespace App\Http\Controllers\Emp\Me;<br />
use App\Http\Controllers\Controller;<br />
class Profile extends Controller<br />
{<br />
<br />
public function show() {<br />
<br />
      dd(Auth::user()->person->full_name);<br />
      return view('emp.me.profile.index');<br />
    }<br />
}<br />

<br />
//// return null in dd();<br />

**Comment by GrahamCampbell** [comment]
I don't see a bu there?

**Comment by GrahamCampbell** [comment]
Auto-presenting only happens when the view event is fired, to variables bound to views.

If you want to present things in a controller, you must actually call the decorator with your model instance.

**Comment by GrahamCampbell** [comment]
```
AutoPresenter::decorate(Auth::user()->person)->full_name;
```

**Comment by GrahamCampbell** [comment]
I'm not sure how you thought we were going to change the semantics of the php code and return a different object there - there is no magic going on.

**Comment by congas1983** [comment]
how could you bring relationships the person
Auth :: user () -> person-> entrepreneur-> entreneur_type   ??

All relationships with person?
